- name: restart kubelet
  service: name=kubelet state=restarted

- name: restart kube-proxy
  service: name=kube-proxy state=restarted

- name: reexecute kubelet.sh
  shell: "{{ kubelet_shell }}"

- name: reexecute proxy.sh
  shell: "{{ kube_proxy_shell }}"
